/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Register */

#ifndef _Included_com_Register
#define _Included_com_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Register
 * Method:    reg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_Register_reg
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_Register
 * Method:    log
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Register_log
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
